"""answer update

Revision ID: ee3f4f86f8f2
Revises: 4c7be5187358
Create Date: 2025-11-13 16:50:36.079098

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ee3f4f86f8f2"
down_revision: Union[str, Sequence[str], None] = "4c7be5187358"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "answers", ["question_id", "text"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "answers", type_="unique")
    # ### end Alembic commands ###
